name: Django CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Django SECRET_KEY
        id: secret
        run: |
          python - <<'PY'
import secrets
print(f"key={secrets.token_urlsafe(50)}")
PY
        shell: bash

      - name: Set environment variables
        run: |
          echo "DEBUG=False" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ steps.secret.outputs.key }}" >> $GITHUB_ENV
          echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> $GITHUB_ENV

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: emergency_ambulance.settings
        run: |
          python manage.py migrate --noinput

      - name: Collect static files
        env:
          DJANGO_SETTINGS_MODULE: emergency_ambulance.settings
        run: |
          python manage.py collectstatic --noinput

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: emergency_ambulance.settings
        run: |
          python manage.py test --verbosity 2


